// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JWTService is an autogenerated mock type for the JWTService type
type JWTService struct {
	mock.Mock
}

// NewToken provides a mock function with given fields: id, email, role
func (_m *JWTService) NewToken(id string, email string, role string) (string, error) {
	ret := _m.Called(id, email, role)

	if len(ret) == 0 {
		panic("no return value specified for NewToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(id, email, role)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(id, email, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(id, email, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTService creates a new instance of JWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTService {
	mock := &JWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
